import Head from "next/head";
import Hero from "../../components/Hero";
import Button from "../../containers/Button";

export default function Proizvodi() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero
        title="Proizvodi"
        subtitle="Home/Proizvodi"
        hero="/images/blackstore1.png"
        small
      ></Hero>
    </>
  );
}
