import Head from "next/head";
import Hero from "../../components/Hero";
import ProductLayout from "../../components/Layout/ProductsLayout";
import ProductsGrid from "../../components/ProductsGrid";
import Sidebar from "../../components/Sidebar";
import { products, categories } from "../../data";

export default function Proizvodi() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ProductLayout>
        <Sidebar categories={categories}></Sidebar>
        <ProductsGrid columns={3} rows={4} products={products} />
      </ProductLayout>
    </>
  );
}
