import Head from "next/head";
import Hero from "../../components/Hero";
import ProductsGrid from "../../components/ProductsGrid/ProductsGrid";
import Sidebar from "../../components/Sidebar";
import { products, categories } from "../../data";
import styled from "styled-components";

export default function Proizvodi() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero
        title="Proizvodi"
        subtitle="Home/Proizvodi"
        hero="/images/blackstore1.png"
        small
      ></Hero>
      <Grid>
        <Sidebar categories={categories}></Sidebar>
        <ProductsGrid columns={3} rows={4} products={products} />
      </Grid>
    </>
  );
}

const Grid = styled.div`
  display: flex;
  background: whitesmoke;
  padding: 5rem;

  & > * {
    flex: 1 1 100%;
  }

  aside {
    flex: 1 0 25%;
  }

  @media (max-width: 500px) {
    flex-wrap: wrap;
    padding: 2rem;
  }
`;
