import Head from "next/head";
import Hero from "../components/Hero";
import Button from "../containers/Button/Button";

export default function Home() {
  return (
    <>
      <Head>
        <title>Safety Tex development</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Hero
        title="Let's growth you business with us"
        subtitle="Skanska is a Swedish based company that has many subsidiaries around Sweden and the world, making them one of the biggest construction companies in the world."
      >
        <Button url="/proizvodi">Getting started</Button>
      </Hero>
    
    </>
  );
}
