import Head from "next/head";
import Hero from "../components/Hero";
import Map from "../components/Map";
import Spacer from "../containers/Spacer";

import { company } from "../data";
import ContactDetails from "../components/ContactDetails/ContactDetails";

export default function Home() {
  return (
    <>
      <Head>
        <title>Safety Tex - Kontakt</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Hero
        title="Contacts"
        subtitle="Home/Contacts"
        hero="/images/kontaktbanner.png"
        small
      ></Hero>
      <Spacer />
      <ContactDetails company={company} />
      <Map></Map>
      <Spacer />
    </>
  );
}
