import Head from "next/head";
import Hero from "../components/Hero";

import { company, staff, clients } from "../data";
import OurOffer from "../components/OurOffer/OurOffer";
import ClientsSlider from "../components/ClientsSlider/ClientsSlider";
import ContactUs from "../components/ContactUs";

export default function Home() {
  return (
    <>
      <Head>
        <title>Safety Tex - O nama</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Hero
        title="O nama"
        subtitle="Home/O nama"
        hero="/images/banner1.png"
        small
      ></Hero>
      <OurOffer staff={staff[0]} />
      <ClientsSlider clients={clients} nav={true}>
        <h1>Our clients</h1>
        <p>
          Blueberries are perennial flowering plants with blue or purple
          berries. To maintain top quality, berries are harvested at least every
          other day.
        </p>
      </ClientsSlider>
      <ContactUs />
    </>
  );
}
