import Head from "next/head";
import Hero from "../components/Hero";

import { company } from "../data";

export default function Home() {
  return (
    <>
      <Head>
        <title>Safety Tex - O nama</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Hero
        title="O nama"
        subtitle="Home/O nama"
        hero="/images/banner1.png"
        small
      ></Hero>
    </>
  );
}
